[package]
name = "googleapis"
version = "0.0.1"
authors = ["Ferrous Systems"]
edition = "2018"

[dependencies.googleapis-raw]
version = "0.0.1"
path = "googleapis-raw"

[workspace]
members = [
  ".",
  "googleapis-raw",
]
