version: 2
jobs:
  build:
    docker:
      - image: rust:1.31
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
workflows:
  version: 2
  build_workflow:
    jobs:
      - build
