[package]
name = "gcp-grpc"
version = "0.0.1"
authors = ["Ferrous Systems"]
edition = "2018"

[dependencies]
futures = "0.1.28"
grpcio = "0.5.0-alpha.1"

[dependencies.gcp-grpc-raw]
version = "0.0.1"
path = "../gcp-grpc-raw"
